# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c18794b03c23838301c3e9074fb38f389a2ed3ae177e87e88d32bfadadd73caf4390b17dd2f87fac5829ffd69a4679fb62a5a65540771cbf322c035a1aa4ef5f

test:
  secret_key_base: 7861e767cdd287b109a25ffcfe2504a1c809dc8c30991c22373db4bb264d615620d650ec10f850f1e7803238da57ca6791bf0a6502259dc62ec304d4794be068

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
